# Generated by Django 2.2 on 2026-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_gay_ass_nigger',
            field=models.BooleanField(default=False),
        ),
    ]
