# Generated by Django 2.2 on 2026-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_userprofile_is_gay_ass_nigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
