# Generated by Django 2.2 on 2026-05-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_gay_ass_nigger',
            new_name='is_black',
        ),
    ]
