# Generated by Django 6.0.5 on 2026-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20260512_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tester',
            field=models.CharField(default='Forced Text', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
